### ISSUE TITLE
Issues for IFC-IF meetings?

### ISSUE THREAD

**Issue by gmn3DS** [buildingSMART/IFC4.x-IF#117]
# Description
Hello,
Some of my colleagues might have input to share regarding Sleepers Placement, so I was looking forward to share the topic with them.
Since I'm not an expert and wouldn't want to distort the context, I have searched for a written description but wasn't able to find one.

# Request
@michelangelo-acca  
Would it be possible for you to open an issue regarding Sleepers Placement ( Similar to was what done for terrain geometry)?

# Suggestion
@evandroAlfieri (and everybody reading this I guess) 
Having these kind of issues allow for sharing scenario and opening the discussion. It also allows people that are not able to attend regularly to still get some info (to some degrees). Plus, it might come in handy for documentation and traceability.
I would suggest for IFC-IF meetings to have at least one issue covering a "big" topic.

**Comment by RickBrice** [comment]
@gmn3DS At the last IF meeting (Oct 19, 2023) you presented a simple model with a single sleeper. Where can I get that model? I'm trying to implement IfcSegmentedGradientCurve geometry for IfcOpenShell and that looks like a good example to start with.

**Comment by michelangelo-acca** [comment]
Hi, I think the folders and descriptions will be created by @evandroAlfieri, in the meantime you can find the reference IFC example file that we created in the attachment.
[ACCA_TestCantSmall.zip](https://github.com/buildingSMART/IFC4.x-IF/files/13164143/ACCA_TestCantSmall.zip)

**Comment by evandroAlfieri** [comment]
@michelangelo-acca I've initiated the readme [here](https://github.com/buildingSMART/IFC4.x-IF/tree/main/IFC-files/Linear-placement-sleepers), please have a look and adjust if I did not summarized your intentions correctly. 

@gmn3DS yes, good suggestion. Usually IF discussions start from issues posted in GH. In this specific case, the issue was posted on the miro board (along with many other input that will need to be organised, prioritised and promoted to GH issues, to track the discussion). That said, for now I'll create a GH issue and refer to the readme just created - so that your colleagues can add their input
