### ISSUE TITLE
MapConversion or RigidOperation, when no transformation/translation are required?

### ISSUE THREAD

**Issue by evandroAlfieri** [buildingSMART/IFC4.x-IF#19]
There is the need to agree on the best pair of IFC entities to be used for the following scenario:

- All data in the IFC file is in map coordinates and map meters
- The target CS is a projected CS
- but no coordinate operation (not transformation, nor translation) is required

**Option 1**
Use _IfcRigidOperation_ with its attributes `FirstCoordinate`, `SecondCoordinate`, `Height` set to `0`.

Example
```
#904 = IFCRIGIDOPERATION(#13, #905, IFCLENGTHMEASURE(0.), IFCLENGTHMEASURE(0.), 0.);
#905 = IFCPROJECTEDCRS('EPSG:6174', $, $, $, $, $, $);
#13 = IFCGEOMETRICREPRESENTATIONCONTEXT($, 'Model', 3, 1.E-4, #14, #16);
#14 = IFCAXIS2PLACEMENT3D(#15, $, $);
#15 = IFCCARTESIANPOINT((0., 0., 0.));
#16 = IFCDIRECTION((0., 1.));
```

**Option 2**
Use _IfcMapConversion_ with its attributes `Eastings`, `Northings`, `OrthogonalHeight` set to `0`, and its `Scale` set to `1` 

Example
```
#904 = IFCMAPCONVERSION(#13, #905, 0., 0., 0., 1., 0., 1.);
#905 = IFCPROJECTEDCRS('EPSG:6174', $, $, $, $, $, $);
#13 = IFCGEOMETRICREPRESENTATIONCONTEXT($, 'Model', 3, 1.E-4, #14, #16);
#14 = IFCAXIS2PLACEMENT3D(#15, $, $);
#15 = IFCCARTESIANPOINT((0., 0., 0.));
#16 = IFCDIRECTION((0., 1.));
```

@LeeGregory12d @pjanck @SergejMuhic what would be the best option in this scenario?

> NOTE: For simplicity, I've made the example using EPSG code to define the CS, but as you know _IfcWellKnownText_ could have been used. That does not affect the scenario.

**Comment by SergejMuhic** [comment]
If you have to convert the coordinates `IfcMapConversion`, if not then `IfcRigidOperation`.

When you say map meters, you probably mean projected coordinates from a curved surface to a circular plane i.e. map, right? In that case no conversion is required and `IfcRigidOperation` is what should be used.

Curious, if this is the understanding of the rest of the group. 😄

**Comment by LeeGregory12d** [comment]
Sorry but I have been out of action for a while.

I agree with Sergej that it is option 1.

The data is already in map metres (that is, Eastings and Northings) and so IfcMapConversion should not be used.

**Comment by LeeGregory12d** [comment]
**Another question - edge cases**

**(a) Data already in map coordinates and map metres**
In option 1, is it necessary to have
 #904 = IFCRIGIDOPERATION(#13, #905, IFCLENGTHMEASURE(0.), IFCLENGTHMEASURE(0.), 0.)
when it is only a zero translation?

Or can IfcRigidOperation be left out?
Or is that asking for trouble?
 
**(b) IfcMapConversion and IfcMapConversion when it is just a unit operation. That is, scales all one, zero rotation and translation**
In this case I believe you **MUST** have the IfcMapConversion/IfcMapConversionScaled because IfcMapConversion/IfcMapConfversionScaled tells you that the data has come from a local engineering coordinate system.

This is extremely important because one has to be aware that the data will be inaccurate if the length covered is too large.
"Too large" would be dependent on the projection, the relationship between the data to the project, accuracy required etc.
 This would be project dependent but the existence of IfcMapConversion/IfcMapConversionScaled warns the receiver to be wary.

**Comment by pjanck** [comment]
+1 for option 1.

**Comment by evandroAlfieri** [comment]
Option1 it is. Thanks all
