### ISSUE TITLE
IfcShapeRepresentation.Identifier for survey points

### ISSUE THREAD

**Issue by evandroAlfieri** [buildingSMART/IFC4.x-IF#20]
**Problem**
*Is your request related to a problem? Please describe.*

Here in Trimble we are still struggling with the value to choose for `IfcShapeRepresentation.Identifier`, for survey points.

We've only found:
- `CoG` for points, which description is: *Point to identify the center of gravity of an element. This value can be used for validation purposes.*
- `Annotation`, but its current description says: *3D annotations not representing elements.* That doesn't seem correct either.

**Solution(s)**
*Describe the solution you'd like. If you have multiple options, list all of them.*

- **Option 1**
Add a new Identifier for covering survey 3D points. Example: `SurveyPoint`

- **Option 2**
Adjust the description of Annotation, so to be used as Identifier for survey points.

**Require schema changes?**
- ` ` yes
- `✓` no
- ` ` don't know

**Require documentation changes?**
- `✓` yes
- ` ` no
- ` ` don't know

**Rule required**
*Need for a formal rule? Describe it*
- `✓` normative check: every IFC file must pass this check
- ` ` good practice check: just triggers a warning, but the IFC file is still valid
- ` ` don't know

> For `IfcShapeRepresentation.Identifier`, only the Identifiers listed in the IFC documentation must be used 

**Additional context**
*Add any other context or screenshots about the feature request here.*

This issue is opened by @evandroAlfieri, starting from a request by @JanErikHoel. This issue will be used to demonstrate: i) the use of the issue template, ii) the IF approval process, iii) the creation of IF agenda's items

**Comment by aothms** [comment]
I find "Body" "Reference" "Annotation" all potential candidates, depending on the use case of exchanging the points. For RepresentationType there is already a PointCloud label (https://github.com/buildingSMART/IFC4.3.x-development/edit/master/docs/schemas/resource/IfcRepresentationResource/Entities/IfcShapeRepresentation.md#l30 (line 30)) so it seems to me geometric representations as point lists was already envisioned as part of the existing identifiers. Therefore I would vote for Option 2 (with annotation or another id label).

May I suggest not to use the github checkmarks because github interprets them as tasks (3 out of 9 tasks completed). Instead you can use unicode checkmarks or anything else that looks pretty.

- ` ` yes
- `✓` no
- ` ` don't know

**Comment by evandroAlfieri** [comment]
just pinging @LeeGregory12d as he might also have an informed opinion on this

**Comment by LeeGregory12d** [comment]
The question of "survey points" came up in the bSI IFC 4X3 Project led by Stefan Jaud in 2020-2021, and the decision was that IfcAnnotation should be used.

Since then, in Australia, a number of Road Authorities have been working with buildingSMART Australasia on a definition for survey points, and even more importantly survey stringlines, using IfcAnnotation, so that all the information they currently require when survey consultants provide them with survey data, can be supplied in an IFC file. 
This includes extra property sets on the survey stringline itself, and each vertex and segment that make up the survey stringline.  

The group is working on common names for the properties they require, and extra user defined PredefinedTypes that they also require. The proposal also covers null z-values that are also critical for any survey.  

The proposed definitions have been tested in ACCAs IFC 4x3 Cloud Viewer, usBIM, and the required survey data and properties sets have all been correctly drawn.

**Note:**
The word "survey string" is normally used in Australia but for this work they reverted to using "survey stringline" so that no one would be confused and thought it was just text.

**Comment by JanErikHoel** [comment]
@Cafougnette : You asked: "Why do you need to set this identifier ? How will you use it ? May be to identify a survey point during the import ? You could set 'identifer' empty (as it is optional), and set a type to the annotation, ('ASBUILTPOINT' ?) (http://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/lexical/IfcAnnotationTypeEnum.htm)"

The answer to this is that this identifier is mandatory (as far as we understand).
From the formal propositions in the documentation:
 EXISTS(SELF\ifcRepresentation.RepresentationIdentifier)

**Comment by JanErikHoel** [comment]
I think the BEST solution would be to make a new ifcShapeRepresentation.Identifier enum value: SurveyPoint

But as the second best solution, I would suggest the following extra explanation for  ifcShapeRepresentation.Identifier = Annotation:  ifcShapeRepresentation.Identifier: _**Survey geometry** or 3D annotations not representing elements_

**Comment by evandroAlfieri** [comment]
> The question of "survey points" came up in the bSI IFC 4X3 Project led by Stefan Jaud in 2020-2021, and the decision was that **IfcAnnotation** should be used.

@LeeGregory12d do you have a sample file using _IfcAnnotation_? I'd like to check which _IfcShapeRepresentation.Identifier_ has been used (if any)

**Comment by Samanii2** [comment]
I like option 1 here. 
I really like when you can get an idea of what a type of information a file contains by just looking in the file without extensive knowledge of the documentation. 

And SurveyPoints are really interesting for us at Adtollo.
